# Generated by Django 3.2.19 on 2023-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('al', 'Algeria'), ('an', 'Angola'), ('be', 'Benin'), ('bo', 'Botswana'), ('bu', 'Burkina Faso'), ('ce', 'Central African Republic (CAR)'), ('ca', 'Cameroon'), ('co', 'Comoros'), ('con', 'Congo, Democratic Republic of the'), ('cong', 'Congo, Republic of the'), ('dj', 'Djibouti'), ('eq', 'Equatorial Guinea'), ('eg', 'Egypt'), ('er', 'Eritrea'), ('et', 'Ethiopia'), ('ga', 'Gabon'), ('gam', 'Gambia'), ('gh', 'Ghana'), ('gu', 'Guinea'), ('gui', 'Guinea-Bissau'), ('ke', 'Kenya'), ('li', 'Liberia'), ('lib', 'Libya'), ('ma', 'Madagascar'), ('mal', 'Malawi'), ('mali', 'Mali'), ('mau', 'Mauritania'), ('mo', 'Morocco'), ('moz', 'Mozambique'), ('na', 'Namibia'), ('ni', 'Niger'), ('nig', 'Nigeria'), ('rw', 'Rwanda'), ('se', 'Senegal'), ('si', 'Sierra Leone'), ('so', 'Somalia'), ('sou', 'South Africa'), ('sout', 'South Sudan'), ('su', 'Sudan'), ('ta', 'Tanzania'), ('to', 'Togo'), ('tu', 'Tunisia'), ('ug', 'Uganda'), ('za', 'Zambia'), ('zi', 'Zimbabwe')], default='normal', max_length=32),
        ),
    ]
