# Generated by Django 3.2.19 on 2023-06-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends12', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_ro9o74', upload_to='images/'),
        ),
    ]
