# Generated by Django 3.2.19 on 2023-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('LOGIN', 'Login issue'), ('REPORT_POST', 'Report a post'), ('GENERAL', 'General Enquiry'), ('DELETE_ACCOUNT', 'Delete Account')], default='GENERAL', max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('message', models.TextField(max_length=500)),
                ('message_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
